[build-system]
  requires = ["setuptools>=68.0"]
  build-backend = "setuptools.build_meta"

[project]
  name = "SieveAI"
  description = "SieveAI: An Automated Drug Discovery Pipeline"
  version = "0.8.dev"
  authors = [
    { name="Vishal Kumar Sahu", email="mail@vishalkumarsahu.in" },
  ]
  readme = "README.md"
  license = {file = "LICENSE"}
  requires-python = ">=3.8, <3.12"
  classifiers = [
    'Operating System :: OS Independent',
    'Intended Audience :: Science/Research',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
  ]
  dependencies = [
    'toml',
    'UtilityLib',
    'biopython',
    'imageio',
    'lxml',
    'numpy',
    'meeko',
    'rdkit-pypi',
    'Pillow',
    'requests',
    'seaborn',
    'vmd-python',
    'streamlit',
  ]

[project.scripts]
  sieveai = "sieveai:dock"
  sieveai_server = "sieveai:server"

[project.urls]
  Homepage = "https://github.com/TheBiomics/SieveAI"
  Issues = "https://github.com/TheBiomics/SieveAI/issues"
